.TH HIJRIAPPLET 1 "Dec 27, 2008"
.SH NAME
HijriApplet \- Hijri Islamic Calendar tray applet
.SH SYNOPSIS
.B HijriApplet [--hidden]
.SH DESCRIPTION
.PP
\fBHijriApplet\fP is a Hijri tray applet for GNOME (also works with KDE) that 
uses Hijra Algorithm by Muayyad Saleh Alsadi provided by python-hijra package.
.IP
.SH OPTIONS
.TP
\fB\-\-hidden\fR
Start the applet without showing the popup window

.SH AUTHOR
HijriApplet was written by Muayyad Saleh Alsadi <alsadi@ojuba.org>
.PP
This manual page was written by Ahmed El-Mahmoudy <aelmahmoudy@sabily.org>, for 
the Debian project (but may be used by others).
